### ISSUE TITLE
Improve Code Logic for Things We've Built Section

### ISSUE THREAD

**Issue by meinhoonharsh** [semikolan-co/semikolan-react#42]
#### Description
The Projects displaying in the **Things We've Built** Section are Currently Hardcoded into HTML/JSX. 
And this is not good practice as well and breaks the DRY Concept. And also It is a bit difficult to manage. So we need to fix it make it more scalable. We can create a JSON file to store data of all projects and render them.

#### Screenshots
![image](https://user-images.githubusercontent.com/64343449/135732912-4b44f646-a21d-418b-94e4-4dffccd60f38.png)

#### Files
`src/component/Work.js` - Here you will get everything about the current **Thing We've Built** Section

#### To Reproduce
To reproduce, just visit [https://semikolan.co](https://semikolan.co) and scroll to Things we've built Section

#### Tasks
- [ ] Create JSON file for Projects (in `src/`)
- [ ] Display all Projects using `foreach` (`map` function here)
- [ ] Change CSS to act different on Odd count Project and different on Even Count Projects

**Comment by chinmaym07** [comment]
Hey @meinhoonharsh  Can I work on this ?

**Comment by meinhoonharsh** [comment]
Yeah Sure, assigned this issue to you
