### ISSUE TITLE
Add Communiy Partners In Section on Home Page 

### ISSUE THREAD

**Issue by meinhoonharsh** [semikolan-co/semikolan-react#70]
## Description
Currently, there is no "Community Partners in Section", So we need to prepare a Community Partners In Section there, where we can simply put on the Logos of all Programs/Events in which we are Community Partners

Title for Section: Community Partners
All Programs/Events in which we are Community Partners:
- [Hack Odisha](https://hackodisha.xyz/)
- [Hack This Fall](https://hackthisfall.tech)
- [Script Winter of Code](https://swoc.scriptindia.org/)
- [Infinite Clone Conspiracy](https://icc21.tech/)

## Files
- `src/pages/Home.js` Contains the Home Components for Home Page
- `src/components/` Directory where you can create Component for it
- `src/assets/image/` Here you can create a separate directory containing Logos of Programs/Events

## To Reproduce
This is an enhancement Issue, so no Reproduction Steps

## Tasks
- [ ] Create Component for this Section
- [ ] Check all Logos are Redirecting to Correct Address
- [ ] Add Component to Home Page
- [ ] Update File Structure in Readme

**Comment by wilsonfurtado2000** [comment]
assign this to me
