### ISSUE TITLE
Add Our Communiy Partners Section on Home Page

### ISSUE THREAD

**Issue by meinhoonharsh** [semikolan-co/semikolan-react#74]
## Description
Currently, there is no "Our Community Partners Section", So we need to prepare an Our Community Partners Section there, where we can simply put on the Logos of all Programs/Events in which we are Community Partners

Title for Section: Our Community Partners
All Communities in which we are Community Partners:
- [GDSC UIT RGPV](https://gdsc.community.dev/university-institute-of-technology-rgpv-bhopal/)
- [CNCF Bhopal](https://community.cncf.io/bhopal/)

## Files
- `src/pages/Home.js` Contains the Home Components for Home Page
- `src/components/` Directory where you can create Component for it
- `src/assets/image/` Here you can create a separate directory containing Logos of Communities

## To Reproduce
This is an enhancement Issue, so no Reproduction Steps

## Tasks
- [ ] Create Component for this Section
- [ ] Check all Logos are Redirecting to Correct Address
- [ ] Add Component to Home Page
- [ ] Update File Structure in Readme

**Comment by ShwetKhatri2001** [comment]
I would like to work on this issue

**Comment by Karan-Dhingra** [comment]
Hi, I have almost completed this page. It will be helpful if you provide logo for both cimmunities.

**Comment by Karan-Dhingra** [comment]
#78 PLEASE CHECK THIS

**Comment by meinhoonharsh** [comment]
Closing this Issue, It's fixed under #78
