### ISSUE TITLE
Improve Community Partners Section

### ISSUE THREAD

**Issue by meinhoonharsh** [semikolan-co/semikolan-react#91]
## Description
Currently, there is a Community Partners Section, which looks like the screenshot attached below, So we need to Upgrade this and provide it a better UI

## Screenshots
![image](https://user-images.githubusercontent.com/64343449/149721528-a00bc3a3-efe7-473e-bfff-d4af165a2987.png)

## Files
A list of relevant files for this issue. This will help people navigate the project and offer some clues of where to start.
`src/component/Community.js` - Contains JSX and logic for Component

## To Reproduce
Just visit https://semikolan.co or go to Index route in Local System

## Tasks
Include specific tasks in the order they need to be done. Include links to specific lines of code where the task should happen at.
- [ ] New UI is matching with the whole Page theme
- [ ] Animations are Working Fine
- [ ] I haven't changed any other file which is not related to this Issue
